'use client';

import React from 'react';
import { Button } from '../ui/button';

function DownloadSummaryButton({
  title,
  summaryText,
  fileName,
  createdAt,
}: {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
}) {
  const handleDownload = () => {
    const summaryContent = `# ${title}
Generated summary
Generated on: ${new Date(createdAt).toLocaleDateString()}

${summaryText}

Original file: ${fileName}
Generated by SummPDF`;

    const blob = new Blob([summaryContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = `Summary-${title.replace(
      /[^a-zA-Z0-9]/g,
      '_'
    )} - ${createdAt}.txt`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  return (
    <Button
      size="sm"
      className="h-8 bg-rose-100 text-rose-600 hover:text-rose-700 hover:bg-rose-50"
      onClick={handleDownload}
    >
      Download summary
    </Button>
  );
}

export default DownloadSummaryButton;
